### PR TITLE
improve: Button Icon prop

### LINKED ISSUE #80: Add an `icon` prop to Button
Icon buttons are pretty common (in general), although currently we have only 1: Login With Github button on Cloud.

It'd be great if this was supported OOTB rather than having to build it outside (and deal with spacing etc.)

### LINKED ISSUE #194: Replace `leadingIcon` and `trailingIcon` props on `Button` with `icon`
Replace with a single prop. Always show the icon on the left.
When we implement internationalization, the icon should automatically show up on the other side for some languages (AKA let Lens control it instead of letting the consumer control it)

### PR DESCRIPTION
**Pull request by ruheni**
Closes #194

### CODE REVIEW

**Review by luanvdw — APPROVED** [review]

**Comment by luanvdw** [comment]
LGTM 👍  Nice work!

I think you can use the "trailingIcon" (on the right of the text) logic from before for when implementing the isLoading prop on #193 regarding the rendering.

**Comment by ruheni** [comment]
Thanks. Sure, I'll update that

**Review by madebysid — APPROVED** [review]
Awesome! Could you also send a PR to cloud updating Lens and accomodating this breaking change?

**Comment by ruheni** [comment]
That may not be necessary. There isn't any use of `trailingIcon` and `leadingIcon` props on cloud. We can let renovate handle the updates of the packages maybe?

**Comment by madebysid** [comment]
Ah okay cool! In that case, we should probably use Button with icon for the login page's Github login button :D

**Pull request merged**
