### PR TITLE
improve: Code Block copy icon + mechanics

### PR DESCRIPTION
**Pull request by luanvdw**
The following updates are in response to the feedback provided for the [Continue locally PR](https://github.com/prisma/cloud/pull/977)

Updated `<Icon />` so that it makes use of tailwinds SVG fill utility: `fillCurrent` instead of a defined text color, so that it will set the fill color of the SVG to the current text color i.e. the text color set from a wrapping parent. This was causing the color of the Icon on the code block to not conform the color defined for the secondary variant on the `<Button />`

Updated the copy mechanics so that the feedback presented to the user takes place on the "Button" itself and does not make use of the toasts.

**!!NOTE** Point 1, may contain breaking changes, as areas where the use of an <Icon /> may have relied on the defined Icon color of `text-gray-400` would now need that applied to its container. Flagging for discussion

**Initial:**

https://user-images.githubusercontent.com/6928171/127782901-dd97963a-4ff5-4619-acfe-d88ceeefc42d.mp4

**Updated:**

https://user-images.githubusercontent.com/6928171/127782908-40a8b9af-3491-40d3-ad25-23d71a6d096c.mp4

### CODE REVIEW

**Comment by madebysid** [comment]
Nice! I didn't know this was a thing!

For the potential breaking change, I suppose the simplest way to confirm is to just go over all Cloud screens and verify, there aren't a lot of them.

**Review by madebysid — APPROVED** [review]

**Comment by madebysid** [comment]
Ah I can already see a bunch of visual changes via Chromatic. Let's make sure we address those before we merge

**Comment by luanvdw** [comment]
@madebysid I updated the implementation where Icon is used elsewhere both within the Lens project, other components using <Icon /> as well as a minor [PR](https://github.com/prisma/cloud/pull/993) in cloud.

This _should_ ensure that we are covered for the possible breaking change, breaking being the incorrect color of the Icon being used.

Once merged I will run through Cloud to make sure incase an lone wolf Icon was missed.

**Comment by luanvdw** [comment]
@madebysid I made changes to all the remaining components that were affected by the Icon color update. Some of the components however passed an actual text value to the Icon, which was never applied as the internal class (now removed) was overriding it. So there may be some additional "corrections" from this.

Once merged, I will bump the lens version from the [Connection string PR](https://github.com/prisma/cloud/pull/991) and then wrap it up with the updates needed from this PR.

**Pull request merged**
